### ISSUE TITLE
React.PropTypes has been deprecated. 

### ISSUE THREAD

**Issue by CarlMungazi** [gyver98/part1-react-tesla-battery-range-calculator-tutorial#1]
`React.PropTypes` has been extracted into its own package (https://www.npmjs.com/package/prop-types) so it might be worth adding a note to the original tutorial, which is great, by the way. My intro to virtual dom came via https://mithril.js.org so it was interesting to compare both.

**Comment by shihlinlu** [comment]
I ran into this issue as well. Here is the corrected file for `TeslaCar.js` after installing prop-types. Need to only add an import statement. 

https://github.com/shihlinlu/tesla-range-calculator/blob/master/src/components/TeslaCar/TeslaCar.js 

@gyver98 could you please update this in the tutorial and source code?

**Comment by gyver98** [comment]
Hi @CarlMungazi  and @shihlinlu,
Thanks for raising the issue.
Please be aware that a note has been added to the original tutorial accordingly. 

![screen shot 2017-06-28 at 8 35 30 pm](https://user-images.githubusercontent.com/5289762/27633143-62783ffa-5c41-11e7-8898-d1682a98d43f.png)

**Comment by shihlinlu** [comment]
Thanks for the update. I'd also recommend updating the source code to replace where `React.PropTypes` were previously declared.

I found another change for TeslaStats. `TeslaStats.propTypes = {
	carstats: PropTypes.array
}`
